get_mask_card_number error: ValueError. Inputs: ('12345678',), {}